pref("extensions.addon@offen.org.description", "chrome://offen/locale/strings.properties");  
pref("extensions.offen.log", true);
pref("extensions.offen.version","");
pref("extensions.offen.loglevel", 1);
pref("extensions.offen.clearlogfileatstarttime", true);
pref("extensions.offen.sound", "default");
pref("extensions.offen.installdir", "");
pref("extensions.offen.activated", true);
pref("extensions.offen.useOneTab",true);
pref("extensions.offen.allowGeolocation","");
pref("extensions.offen.test.mode",false);
pref("extensions.offen.test.latitude","49.450383");
pref("extensions.offen.test.longitude","11.085463");
pref("extensions.offen.search.maxResults",15);
